### ISSUE TITLE
LLVM 7.1 support

### ISSUE THREAD

**Issue by mshabunin** [intel/llvm-patches#1]
Version check here: https://github.com/intel/llvm-patches/blob/703b033a0d4d2f555cd7fea35c9634aa5786585a/CMakeLists.txt#L209-L211 does not work with the latest _release_70_ branch from LLVM repository, because version have been bumped to 7.1.0: https://github.com/llvm-mirror/llvm/commit/2883e0bc28b27e7eec068472557528baf08d0e0c

**Comment by lwesiers** [comment]
It was fixed with 3d4449ff6f8ae8b8f1f4258c36a57f77f9ca8491.

Closing the issue.
